name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      frontend-folder: .

    steps:
      - uses: actions/checkout@v2

      - name: Instal npm packages
        run: npm install
        working-directory: ${{env.frontend-folder}}

      - name: Run application
        run: npm start &
        working-directory: ${{env.frontend-folder}}

      - name: Run lint
        run: npm run lint
        working-directory: ${{env.frontend-folder}}

      - name: Run cypress
        run: npx cypress run --record --key 9e055824-71df-490e-adef-d984dff9e547
        working-directory: ${{env.frontend-folder}}
