name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      frontend-folder: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Instal npm packages
        run: npm install
        working-directory: ${{env.frontend-folder}}

      - name: Run application
        run: npm start &
        working-directory: ${{env.frontend-folder}}

      - name: Run cypress
        run: npx cypress run
        working-directory: ${{env.frontend-folder}}
