name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: self-hosted
    env:
      frontend-folder: .

    steps:
      - uses: actions/checkout@v2

      - name: Instal npm packages
        run: npm install
        working-directory: ${{env.frontend-folder}}

      - name: Run application
        run: npm start &
        working-directory: ${{env.frontend-folder}}

      - name: Run lint
        run: npm run lint-warn
        working-directory: ${{env.frontend-folder}}

      - name: Run cypress
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --parallel
        working-directory: ${{env.frontend-folder}}
