name: CI

on: [push]

jobs:
  cypress:
    name: Cypress run
    runs-on: self-hosted
    strategy:
        fail-fast: false
        matrix:
            containers: [1, 2, 3, 4, 5]
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install npm packages
          run: npm install

        - name: Run lint
          run: npm run lint-warn

        - name: Run cypress
          uses: cypress-io/github-action@v2
          with:
              record: true
              parallel: true
              start: npm start
          env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
