name: CI

on: [push]

jobs:
  cypress:
    name: Cypress check
    runs-on: self-hosted
    strategy:
        fail-fast: false
        matrix:
            containers: [1, 2, 3, 4, 5]
    steps:
        - name: Checkout project
          uses: actions/checkout@v2
        
        - name: Read cypress config
          id: read_config
          run: |
            content=`cat cypress.json`
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            echo "::set-output name=cypressConfig::$content"
        
        - name: Run Cypress
          uses: cypress-io/github-action@v2
          with:
              wait-on: ${{ env.APPLICATION_URL }}
              group: 'Nurse project workers'
              record: true
              parallel: true
              start: npm start
              browser: electron
              headless: true
          env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              APPLICATION_URL: ${{ fromJson(steps.read_config.outputs.cypressConfig).env.baseUrl }}
